%SOAL 1

%MATRIKS
A=[1 2 3;2 1 1;3 2 1]
B=[4 4 5;6 1 2;3 5 5]

%DENGAN MENGGUNAKAN MATLAB TEMUKAN

%A.DETERMINAN MATRIKS
C=det(A)
C=det(B)

%B.UKURAN DARI MATRIK
C=size(A)
C=size(B)

%C.TRACE DARI MATRIK A DAN MATRIK B
C=trace(A)
C=trace(B)

%D.NORM MATRIK A DAN MATRIK B
C=norm(A)
C=norm(B)

%E
C=A+B

%F
C=A-B

%G
C=A*B

%H
C=A.*B

%I
C=A^2

%J
C=A.^2

%K.TRANSPOSE DARI MATRIK A DAN MATRIK B
C=A'
C=B'

%L
C=A./B

%M
C=A.\B

%N
C=A/B

%O.INVERS DARI MATRIK A DAN MATRIK B
C=inv(A)
C=inv(B)

%P
C=null(A)

%Q
C=orth(A)

%R
C=rref(A)

%S.NILAI EIGEN DARI MATRIK A DAN MATRIK B
C=eig(A)
C=eig(B)

%T.NILAI SINGULAR DARI MATRIK A DAN MATRIK B
C=svd(A)
C=svd(B)

%U.MATRIK SEGITIGA ATAS DARI MATRIK A DAN MATRIK B
C=triu(A)
C=triu(B)

%V.MATRIK SEGITIGA BAWAH DARI MATRIK A DAN MATRIK B
C=tril(A)
C=tril(B)

%W.TENTUKAN NILAI MAKSIMUM DARI ELEMEN-ELEMEN MATRIK A DAN MATRIK B
C=max(A)
C=max(B)

%X.TENTUKAN NILAI MINIMUM DARI ELEMEN-ELEMEN MATRIK A DAN MATRIK B
C=min(A)
C=min(B)

%Y.TENTUKAN JUMLAH KOLOM ELEMEN-ELEMEN MATRIK A DAN MATRIK B
C=sum(A,1)
C=sum(A,2)
C=sum(B,1)
C=sum(B,2)

%Z.TENTUKAN DIAGONAL DARI MATRIK A DAN MATRIK B
C=diag(A)
C=diag(B)

%SOAL2
%DENGAN MENGGUNAKAN MATLAB

%A.MATRIK IDENTITAS DENGAN DIMENSI 5X5
A=eye(5)

%B.MATRIK DENGAN DIMENSI 3X3 DENGAN ELEMEN-ELEMEN SEMUANYA BERNILAI NOL
A=zeros(3,3)

%C.MATRIK DENGAN DIMENSI 4X4 DENGAN ELEMEN-ELEMEN SEMUANYA BERNILAI SATU
A=ones(4,4)

%D.MATRIK DENGAN DIMENSI 3X4 DIMANA ELEMEN-ELEMEN TERDRITIBUSI ANTARA 0 DAN
%1 (DEFAULT N=M)
A=rand(3,4)

%E.MATRIK DENGAN DIMENSI 3X4 DIMANA ELEMEN-ELEMEN TERDITRIBUSI NORMAL
A=randn(3,4)

